/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

/**
 *
 * @author ASUS
 */
public class Abonne extends javax.swing.JFrame {

    /**
     * Creates new form Abonne
     */
    public Abonne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGO = new javax.swing.JLabel();
        bcommande = new javax.swing.JButton();
        bdesabonne = new javax.swing.JButton();
        navbar = new javax.swing.JLabel();
        llisterevue = new javax.swing.JLabel();
        iconeclearrecherche = new javax.swing.JLabel();
        trecherche = new javax.swing.JTextField();
        iconsearch = new javax.swing.JLabel();
        pscientifique = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tscientifique = new javax.swing.JTable();
        ppolitique = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpolitique = new javax.swing.JTable();
        psportive = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tsportive = new javax.swing.JTable();
        deconnection = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-vertmin.png"))); // NOI18N
        getContentPane().add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 60));

        bcommande.setBackground(new java.awt.Color(69, 98, 78));
        bcommande.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bcommande.setForeground(new java.awt.Color(216, 191, 159));
        bcommande.setText("Commander");
        getContentPane().add(bcommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 110, 30));

        bdesabonne.setBackground(new java.awt.Color(69, 98, 78));
        bdesabonne.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bdesabonne.setForeground(new java.awt.Color(216, 191, 159));
        bdesabonne.setText("S'abonner");
        bdesabonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdesabonneActionPerformed(evt);
            }
        });
        getContentPane().add(bdesabonne, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 100, 30));

        navbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond bege navbar.png"))); // NOI18N
        getContentPane().add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 60));

        llisterevue.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N
        llisterevue.setForeground(new java.awt.Color(240, 240, 240));
        llisterevue.setText("Listes De  Revues :");
        getContentPane().add(llisterevue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        iconeclearrecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconsX.png"))); // NOI18N
        getContentPane().add(iconeclearrecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 30, 30));

        trecherche.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        trecherche.setText("          ");
        trecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trechercheActionPerformed(evt);
            }
        });
        getContentPane().add(trecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 280, 30));

        iconsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons search.png"))); // NOI18N
        getContentPane().add(iconsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 30, 30));

        pscientifique.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scientifique :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        pscientifique.setForeground(new java.awt.Color(255, 255, 255));
        pscientifique.setOpaque(false);
        pscientifique.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tscientifique.setBackground(new java.awt.Color(216, 191, 159));
        tscientifique.setForeground(new java.awt.Color(255, 255, 255));
        tscientifique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tscientifique);

        pscientifique.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 860, 100));

        getContentPane().add(pscientifique, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 900, 150));

        ppolitique.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Politique :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        ppolitique.setOpaque(false);
        ppolitique.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpolitique.setBackground(new java.awt.Color(216, 191, 159));
        tpolitique.setForeground(new java.awt.Color(255, 255, 255));
        tpolitique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tpolitique);

        ppolitique.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 860, 110));

        getContentPane().add(ppolitique, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 900, 170));

        psportive.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sportive :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        psportive.setOpaque(false);
        psportive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tsportive.setBackground(new java.awt.Color(216, 191, 159));
        tsportive.setForeground(new java.awt.Color(255, 255, 255));
        tsportive.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tsportive);

        psportive.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 860, 110));

        getContentPane().add(psportive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 900, 150));

        deconnection.setBackground(new java.awt.Color(69, 98, 78));
        deconnection.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deconnection.setForeground(new java.awt.Color(216, 191, 159));
        deconnection.setText("Se deconnecter");
        getContentPane().add(deconnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 643, -1, 30));

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Font verte.png"))); // NOI18N
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trechercheActionPerformed

    private void bdesabonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdesabonneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdesabonneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Abonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Abonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Abonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Abonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Abonne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton bcommande;
    private javax.swing.JButton bdesabonne;
    private javax.swing.JButton deconnection;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel iconeclearrecherche;
    private javax.swing.JLabel iconsearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel llisterevue;
    private javax.swing.JLabel navbar;
    private javax.swing.JPanel ppolitique;
    private javax.swing.JPanel pscientifique;
    private javax.swing.JPanel psportive;
    private javax.swing.JTable tpolitique;
    private javax.swing.JTextField trecherche;
    private javax.swing.JTable tscientifique;
    private javax.swing.JTable tsportive;
    // End of variables declaration//GEN-END:variables
}
