/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Beans.Commande;
import Beans.Lecteurs;
import Models.Connexion;
import static Vue.MC.jpassword;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Commander extends javax.swing.JFrame {

    Connexion c = new Connexion();
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel dt = new DefaultTableModel();

    /**
     * Creates new form Commander
     */
    public Commander() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btncommander = new java.awt.Button();
        tccv = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        tcarte = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tnom = new javax.swing.JTextField();
        tprenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 49, 9));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(235, 222, 212));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 49, 9));
        jLabel2.setText("Passez au payement");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 33, 300, 27));

        jLabel4.setBackground(new java.awt.Color(69, 98, 78));
        jLabel4.setForeground(new java.awt.Color(69, 98, 78));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 186, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(69, 98, 78));
        jLabel6.setText("Code CVV");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 246, -1, -1));

        btncommander.setActionCommand("Je commande");
        btncommander.setBackground(new java.awt.Color(20, 49, 9));
        btncommander.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btncommander.setForeground(new java.awt.Color(255, 255, 255));
        btncommander.setLabel("Je commande");
        btncommander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncommanderActionPerformed(evt);
            }
        });
        jPanel2.add(btncommander, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 354, 189, 36));

        tccv.setBackground(new java.awt.Color(227, 202, 171));
        tccv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tccvActionPerformed(evt);
            }
        });
        jPanel2.add(tccv, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 267, 300, 41));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(69, 98, 78));
        jLabel7.setText("Numéro de carte EDAHABIA");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 165, -1, -1));

        tcarte.setBackground(new java.awt.Color(227, 202, 171));
        tcarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcarteActionPerformed(evt);
            }
        });
        jPanel2.add(tcarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 193, 300, 42));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(69, 98, 78));
        jLabel1.setText("Nom");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 95, -1, -1));

        tnom.setBackground(new java.awt.Color(227, 202, 171));
        jPanel2.add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 116, 133, 37));

        tprenom.setBackground(new java.awt.Color(227, 202, 171));
        jPanel2.add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 116, 153, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 98, 78));
        jLabel3.setText("Prénom");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 95, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 370, 420));

        navbar.setBackground(new java.awt.Color(227, 202, 171));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-vertmin.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        navbar.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 20, -1, -1));

        jPanel1.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncommanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncommanderActionPerformed
        String nom = tnom.getText();
        String prenom = tprenom.getText();
        String carte = tcarte.getText();
        String cvv = new String(tccv.getPassword());
        // Regex pattern for nom et prenom validation
        String nameRegex = "^[a-zA-ZÀ-ÿ\\s]{2,}$";

        // Vérifie si le nom correspond au motif regex
        if (!nom.matches(nameRegex)) {
            JOptionPane.showMessageDialog(null, "Nom invalide ! Le nom doit contenir au moins 2 lettres et peut inclure des espaces.");
            return;
        }

        // Vérifie si le prénom correspond au motif regex
        if (!prenom.matches(nameRegex)) {
            JOptionPane.showMessageDialog(null, "Prénom invalide ! Le prénom doit contenir au moins 2 lettres et peut inclure des espaces.");
            return;
        }
        Commande lec = new Commande();
        lec.setNom(nom);
        lec.setPrenom(prenom);
        lec.setCarte(carte);
        lec.setCvv(cvv);
        try {
            st = c.getCo().createStatement();
            st.executeUpdate("INSERT INTO commande(nomLecteur,prenomLecteur,carte,cvv)VALUES('" + lec.getNom() + "','" + lec.getPrenom() + "','" + lec.getCarte() + "','" + lec.getCvv() + "')");
            Recu recu = new Recu();
            recu.setVisible(true);
            this.setVisible(false);
            recu.pack();
            recu.setLocationRelativeTo(null);
            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(Commander.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btncommanderActionPerformed

    private void tccvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tccvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tccvActionPerformed

    private void tcarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcarteActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Lecteur login = new Lecteur();
        login.setVisible(true);
        this.setVisible(false);
        login.pack();
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commander().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btncommander;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel navbar;
    private javax.swing.JTextField tcarte;
    private javax.swing.JPasswordField tccv;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField tprenom;
    // End of variables declaration//GEN-END:variables
}
