package Vue;

public class MC extends javax.swing.JFrame {

    /**
     * Creates new form MC
     */
    public MC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelconnex = new javax.swing.JPanel();
        connexionlabel = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        mdptxt = new javax.swing.JTextField();
        emaillab = new javax.swing.JLabel();
        mdplab = new javax.swing.JLabel();
        btnconnex = new java.awt.Button();
        jaipasdecompte = new javax.swing.JLabel();
        rediriger_inscription = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(20, 49, 9));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelconnex.setBackground(new java.awt.Color(227, 202, 171));

        connexionlabel.setBackground(new java.awt.Color(255, 255, 255));
        connexionlabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        connexionlabel.setForeground(new java.awt.Color(69, 98, 78));
        connexionlabel.setText("Connexion");
        connexionlabel.setMaximumSize(new java.awt.Dimension(51, 18));

        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });

        emaillab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emaillab.setForeground(new java.awt.Color(69, 98, 78));
        emaillab.setText("E-mail");
        emaillab.setToolTipText("");

        mdplab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mdplab.setForeground(new java.awt.Color(69, 98, 78));
        mdplab.setText("Mot de passe");

        btnconnex.setActionCommand("Connexion");
        btnconnex.setBackground(new java.awt.Color(20, 49, 9));
        btnconnex.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnconnex.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        btnconnex.setForeground(new java.awt.Color(255, 255, 255));
        btnconnex.setLabel("Se connecter\n");
        btnconnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconnexActionPerformed(evt);
            }
        });

        jaipasdecompte.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jaipasdecompte.setForeground(new java.awt.Color(255, 255, 255));
        jaipasdecompte.setText("Je n'ai pas de compte ?");

        rediriger_inscription.setBackground(new java.awt.Color(227, 202, 171));
        rediriger_inscription.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rediriger_inscription.setForeground(new java.awt.Color(20, 49, 9));
        rediriger_inscription.setText("Je m'inscris");
        rediriger_inscription.setToolTipText("");
        rediriger_inscription.setBorder(null);
        rediriger_inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rediriger_inscriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelconnexLayout = new javax.swing.GroupLayout(panelconnex);
        panelconnex.setLayout(panelconnexLayout);
        panelconnexLayout.setHorizontalGroup(
            panelconnexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelconnexLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jaipasdecompte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rediriger_inscription)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelconnexLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelconnexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelconnexLayout.createSequentialGroup()
                        .addGroup(panelconnexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emaillab)
                            .addComponent(mdplab)
                            .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mdptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelconnexLayout.createSequentialGroup()
                        .addComponent(connexionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelconnexLayout.createSequentialGroup()
                        .addComponent(btnconnex, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        panelconnexLayout.setVerticalGroup(
            panelconnexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelconnexLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(connexionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(emaillab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(mdplab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mdptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnconnex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelconnexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jaipasdecompte)
                    .addComponent(rediriger_inscription))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnconnex.getAccessibleContext().setAccessibleName("Se connecter");

        background.add(panelconnex, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 330, 410));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" sur votre site de revues nationales ");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyez les bienvenues");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 530, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/akh2.png"))); // NOI18N
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 350, 160));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 872, 478));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void btnconnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconnexActionPerformed
        Lecteur sign = new Lecteur();
        sign.setVisible(true);
        sign.pack();
        sign.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnconnexActionPerformed

    private void rediriger_inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rediriger_inscriptionActionPerformed
        inscription sign = new inscription();
        sign.setVisible(true);
        sign.pack();
        sign.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_rediriger_inscriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private java.awt.Button btnconnex;
    private javax.swing.JLabel connexionlabel;
    private javax.swing.JLabel emaillab;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jaipasdecompte;
    private javax.swing.JLabel mdplab;
    private javax.swing.JTextField mdptxt;
    private javax.swing.JPanel panelconnex;
    private javax.swing.JButton rediriger_inscription;
    // End of variables declaration//GEN-END:variables
}
