package Vue;

import Models.*;
import Beans.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class MC extends javax.swing.JFrame {

    /**
     * Creates new form MC
     */
    public MC() {
        initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelconnex = new javax.swing.JPanel();
        connexionlabel = new javax.swing.JLabel();
        emaillab = new javax.swing.JLabel();
        mdplab = new javax.swing.JLabel();
        bconnection = new java.awt.Button();
        jaipasdecompte = new javax.swing.JLabel();
        rediriger_inscription = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        temail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(20, 49, 9));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelconnex.setBackground(new java.awt.Color(227, 202, 171));
        panelconnex.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        connexionlabel.setBackground(new java.awt.Color(255, 255, 255));
        connexionlabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        connexionlabel.setForeground(new java.awt.Color(69, 98, 78));
        connexionlabel.setText("Connexion");
        connexionlabel.setMaximumSize(new java.awt.Dimension(51, 18));
        panelconnex.add(connexionlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        emaillab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emaillab.setForeground(new java.awt.Color(69, 98, 78));
        emaillab.setText("E-mail");
        emaillab.setToolTipText("");
        panelconnex.add(emaillab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        mdplab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mdplab.setForeground(new java.awt.Color(69, 98, 78));
        mdplab.setText("Mot de passe");
        panelconnex.add(mdplab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        bconnection.setActionCommand("Connexion");
        bconnection.setBackground(new java.awt.Color(20, 49, 9));
        bconnection.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bconnection.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        bconnection.setForeground(new java.awt.Color(255, 255, 255));
        bconnection.setLabel("Se connecter\n");
        bconnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconnectionActionPerformed(evt);
            }
        });
        panelconnex.add(bconnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 177, 40));
        bconnection.getAccessibleContext().setAccessibleName("Se connecter");

        jaipasdecompte.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jaipasdecompte.setForeground(new java.awt.Color(255, 255, 255));
        jaipasdecompte.setText("Je n'ai pas de compte ?");
        panelconnex.add(jaipasdecompte, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 352, -1, -1));

        rediriger_inscription.setBackground(new java.awt.Color(227, 202, 171));
        rediriger_inscription.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rediriger_inscription.setForeground(new java.awt.Color(20, 49, 9));
        rediriger_inscription.setText("Je m'inscris");
        rediriger_inscription.setToolTipText("");
        rediriger_inscription.setBorder(null);
        rediriger_inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rediriger_inscriptionActionPerformed(evt);
            }
        });
        panelconnex.add(rediriger_inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 352, -1, -1));

        jpassword.setMargin(new java.awt.Insets(2, 6, 2, 6));
        panelconnex.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 220, 290, 39));

        temail.setMargin(new java.awt.Insets(2, 6, 2, 6));
        panelconnex.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 130, 290, 39));

        background.add(panelconnex, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 330, 410));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" sur votre site de revues nationales ");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyez les bienvenues");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 420, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/akh2.png"))); // NOI18N
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 350, 160));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 872, 478));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bconnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconnectionActionPerformed
        ConnexionLecteurs cu = new ConnexionLecteurs();
        boolean trouve = false;
        String email = temail.getText();
        String password = new String(jpassword.getPassword());

        // Regex pattern for email validation
        String emailRegex = "^[a-zA-Z0-9+._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,7}$";

        // Regex pattern for password validation (minimum 8 caractères et au moins un chiffre)
        String passwordRegex = "^(?=.*[0-9]).{8,}$";

        // Vérifie si l'email correspond au motif regex
        if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(null, "Adresse e-mail invalide !");
            return;
        }

// Vérifie si le mot de passe correspond au motif regex
        if (!password.matches(passwordRegex)) {
            JOptionPane.showMessageDialog(null, "Mot de passe invalide ! \nLe mot de passe doit contenir au moins 8 caractères, \ndont au moins un chiffre.");
            return;
        }
        try {
            while (cu.rs.next()) {
                if (temail.getText().equals(cu.rs.getString("email")) && jpassword.getText().equals(cu.rs.getString("mdp"))) {
                    trouve = true;
                    break;
                }

            }
            if (trouve) {
                new Lecteur().setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Email ou mot de passe incorrecte", "erreur", JOptionPane.WARNING_MESSAGE);
                temail.setText(null);
                jpassword.setText(null);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bconnectionActionPerformed

    private void rediriger_inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rediriger_inscriptionActionPerformed
        Inscription sign = new Inscription();
        sign.setVisible(true);
        sign.pack();
        sign.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_rediriger_inscriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private java.awt.Button bconnection;
    private javax.swing.JLabel connexionlabel;
    private javax.swing.JLabel emaillab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jaipasdecompte;
    public static javax.swing.JPasswordField jpassword;
    private javax.swing.JLabel mdplab;
    private javax.swing.JPanel panelconnex;
    private javax.swing.JButton rediriger_inscription;
    public static javax.swing.JTextField temail;
    // End of variables declaration//GEN-END:variables
}
