/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Models.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Panier extends javax.swing.JFrame {

    Connexion c = new Connexion();
    Statement st;
    PreparedStatement ps;
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel model;
    public ResultSet rs;
    String revue;
    int prix;

    /**
     * Creates new form Panier
     */
    public Panier() {
        initComponents();
        ConnexionPanier cs = new ConnexionPanier();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            ps = c.getCo().prepareStatement("SELECT * FROM panier");
            rs = ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(Panier.class.getName()).log(Level.SEVERE, null, ex);
        }

        dtm.addColumn("Nom Revue");

        dtm.addColumn("Prix");

        try {
            while (cs.rs.next()) {
                dtm.addRow(new Object[]{cs.rs.getString("nomrevue"), cs.rs.getFloat("prix")});

            }
            tabpanier.setModel(dtm);
            totale();
        } catch (SQLException ex) {
            Logger.getLogger(Panier.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void totale() {
        float total = 0;
        for (int i = 0; i < tabpanier.getRowCount(); i++) {
            total = total + Float.parseFloat(tabpanier.getValueAt(i, 1) + "");
        }
        txtprix.setText(total + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btncmd = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabpanier = new javax.swing.JTable();
        txtprix = new javax.swing.JTextField();
        navbar = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        jaipasdecompte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(20, 49, 9));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(235, 222, 212));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 49, 9));
        jLabel2.setText("Votre Commande");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 286, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(69, 98, 78));
        jLabel5.setText("Articles Choisis");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(69, 98, 78));
        jLabel6.setText("Prix Total");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        btncmd.setBackground(new java.awt.Color(20, 49, 9));
        btncmd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btncmd.setForeground(new java.awt.Color(255, 255, 255));
        btncmd.setLabel("Je Commande");
        btncmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncmdActionPerformed(evt);
            }
        });
        jPanel3.add(btncmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 189, 36));
        btncmd.getAccessibleContext().setAccessibleName("");

        tabpanier.setBackground(new java.awt.Color(228, 230, 217));
        tabpanier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom Revue", "Prix"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabpanier.setGridColor(new java.awt.Color(228, 230, 217));
        tabpanier.setOpaque(false);
        tabpanier.setSelectionBackground(new java.awt.Color(228, 230, 217));
        jScrollPane1.setViewportView(tabpanier);
        if (tabpanier.getColumnModel().getColumnCount() > 0) {
            tabpanier.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 670, 170));

        txtprix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprixActionPerformed(evt);
            }
        });
        jPanel3.add(txtprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 280, 40));

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 720, 430));

        navbar.setBackground(new java.awt.Color(227, 202, 171));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-vertmin.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        navbar.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        background.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        jaipasdecompte.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jaipasdecompte.setForeground(new java.awt.Color(255, 255, 255));
        jaipasdecompte.setText("Je n'ai pas de compte ?");
        background.add(jaipasdecompte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncmdActionPerformed
        Commander cmd2 = new Commander();
        cmd2.setVisible(true);
        this.setVisible(false);
        cmd2.pack();
        cmd2.setLocationRelativeTo(null);
    }//GEN-LAST:event_btncmdActionPerformed

    private void txtprixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprixActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Lecteur login = new Lecteur();
        login.setVisible(true);
        this.setVisible(false);
        login.pack();
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private java.awt.Button btncmd;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jaipasdecompte;
    private javax.swing.JPanel navbar;
    public static javax.swing.JTable tabpanier;
    public static javax.swing.JTextField txtprix;
    // End of variables declaration//GEN-END:variables
}
